"""post split duration mm:ss enhancements

Revision ID: 4af60bff366a
Revises: b52dcdfaf3ae
Create Date: 2026-05-15 17:03:39.380765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4af60bff366a'
down_revision = 'b52dcdfaf3ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_distance_miles', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('run_type', sa.String(length=20), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('race_name', sa.String(length=200), nullable=True),
    sa.Column('race_distance_miles', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mile_splits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('split_index', sa.Integer(), nullable=False),
    sa.Column('distance_miles', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('time_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['run_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'split_index', name='unique_run_split_index')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mile_splits')
    op.drop_table('run_entries')
    # ### end Alembic commands ###
